### PR TITLE
Update build script to automatically copy the latest source code into the release folder

### PR DESCRIPTION
**Pull request by isaactsg**
This commit removes all the old source code from the resources folder.
It now copies the newest source files from the packages into the resources folder at compile time to ensure that the files on release are the newest version.
It also fixes an issue with Photogrammetry, as in a recent commit a folder was deleted. This new build script accounts for the missing folder.

KNOWN ISSUES:
Within WhiteboxAPI there are 2 pairs of files with the same names (Util.java and Parallel.java). To solve this the files will either need to renamed, or I can make a special case to rename them only in the source_files folder.

### CODE REVIEW

**Comment by isaactsg** [comment]
I also have not yet tested this on Windows yet. Will do tonight and report. Probably should have done that before making the pull request...

**Comment by jblindsay** [comment]
There are no plugin tools in the WhiteboxAPI folder, so the name collisions should not cause any issues. There is no need to copy the WhiteboxAPI code into the resources/source_files folder.

**Comment by isaactsg** [comment]
So I should not copy the source files from the WhiteboxAPI package, or the WhiteboxGIS package?

**Comment by jblindsay** [comment]
That's right Isaac. There's no need to copy any of the WhiteboxAPI, WhiteboxGIS, or RasterCalculator contents.

**Comment by isaactsg** [comment]
I have updated the script to not copy those files

**Comment by jblindsay** [comment]
Great, once you've had a chance to test on Windows, let me know and I'll merge the changes. Thanks again.

**Comment by isaactsg** [comment]
Tested on windows and fixed a typo I made.
All good on windows now.

**Comment by jblindsay** [comment]
Well done Isaac! Thanks once more.

**Pull request merged**
